name = "drevil-proxy"
main = "src/index.js"
compatibility_date = "2025-01-01"

# IMAGE_API_KEY secret must be set via: wrangler secret put IMAGE_API_KEY

[[kv_namespaces]]
binding = "REPORTS"
id = "6da7cca754c24b159cea1d85ee68477e"
